In [1]:
import pandas as pd
data=pd.read_csv('C:\\Users\\user\\Downloads\\WA_Fn-UseC_-Sales-Win-Loss.csv')

In [2]:
data.head()
print(data.head())
data.head(n=2)
data.tail()
data.dtypes

   Opportunity Number     Supplies Subgroup          Supplies Group  \
0             1641984  Exterior Accessories         Car Accessories
1             1658010  Exterior Accessories         Car Accessories
2             1674737      Motorcycle Parts  Performance & Non-auto
3             1675224         Shelters & RV  Performance & Non-auto
4             1689785  Exterior Accessories         Car Accessories

      Region Route To Market  Elapsed Days In Sales Stage Opportunity Result  \
0  Northwest    Fields Sales                           76                Won
1    Pacific        Reseller                           63               Loss
2    Pacific        Reseller                           24                Won
3    Midwest        Reseller                           16               Loss
4    Pacific        Reseller                           69               Loss

   Sales Stage Change Count  Total Days Identified Through Closing  \
0                        13                                    104
1                         2                                    163
2                         7                                     82
3                         5                                    124
4                        11                                     91

   Total Days Identified Through Qualified  Opportunity Amount USD  \
0                                      101                       0
1                                      163                       0
2                                       82                    7750
3                                      124                       0
4                                       13                   69756

   Client Size By Revenue  Client Size By Employee Count  \
0                       5                              5
1                       3                              5
2                       1                              1
3                       1                              1
4                       1                              1

   Revenue From Client Past Two Years Competitor Type  \
0                                   0         Unknown
1                                   0         Unknown
2                                   0         Unknown
3                                   0           Known
4                                   0         Unknown

   Ratio Days Identified To Total Days  Ratio Days Validated To Total Days  \
0                              0.69636                            0.113985
1                              0.00000                            1.000000
2                              1.00000                            0.000000
3                              1.00000                            0.000000
4                              0.00000                            0.141125

   Ratio Days Qualified To Total Days  Deal Size Category
0                            0.154215                   1
1                            0.000000                   1
2                            0.000000                   1
3                            0.000000                   1
4                            0.000000                   4

Opportunity Number                           int64
Supplies Subgroup                           object
Supplies Group                              object
Region                                      object
Route To Market                             object
Elapsed Days In Sales Stage                  int64
Opportunity Result                          object
Sales Stage Change Count                     int64
Total Days Identified Through Closing        int64
Total Days Identified Through Qualified      int64
Opportunity Amount USD                       int64
Client Size By Revenue                       int64
Client Size By Employee Count                int64
Revenue From Client Past Two Years           int64
Competitor Type                             object
Ratio Days Identified To Total Days        float64
Ratio Days Validated To Total Days         float64
Ratio Days Qualified To Total Days         float64
Deal Size Category                           int64
dtype: object

In [3]:
[A,B,C,D,E]

NameError: name 'A' is not defined

In [4]:
from sklearn import preprocessing as pp

In [5]:
label_encoder=pp.LabelEncoder()
encoder_result=label_encoder.fit_transform(["A","B","C","D","E"])
print(encoder_result)

[0 1 2 3 4]

In [6]:
print("Supplies Subgroup",data['Supplies Subgroup'].unique())
print("route to market:",data['Route To Market'].unique())
print("Oppourtunity Result", data['Opportunity Result'].unique())
print("competitor type",data['Competitor Type'].unique())
print("Supplies Group",data['Supplies Group'].unique())

Supplies Subgroup ['Exterior Accessories' 'Motorcycle Parts' 'Shelters & RV'
 'Garage & Car Care' 'Batteries & Accessories' 'Performance Parts'
 'Towing & Hitches' 'Replacement Parts' 'Tires & Wheels'
 'Interior Accessories' 'Car Electronics']
route to market: ['Fields Sales' 'Reseller' 'Other' 'Telesales' 'Telecoverage']
Oppourtunity Result ['Won' 'Loss']
competitor type ['Unknown' 'Known' 'None']
Supplies Group ['Car Accessories' 'Performance & Non-auto' 'Tires & Wheels'
 'Car Electronics']

In [7]:
data['Supplies Subgroup']=label_encoder.fit_transform(data['Supplies Subgroup'])

In [8]:
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,2,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,2,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,5,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,8,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,2,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [9]:
data['Supplies Subgroup']=label_encoder.fit_transform(data['Supplies Subgroup'])
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,2,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,2,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,5,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,8,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,2,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [10]:
data['Region']=label_encoder.fit_transform(data['Region'])
data['Route To Market']=label_encoder.fit_transform(data['Route To Market'])
data['Competitor Type']=label_encoder.fit_transform(data['Competitor Type'])
data['Supplies Group']=label_encoder.fit_transform(data['Supplies Group'])
data['Route To Market']=label_encoder.fit_transform(data['Route To Market'])
data['Opportunity Result']=label_encoder.fit_transform(data['Opportunity Result'])
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,2,0,3,0,76,1,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,1658010,2,0,4,2,63,0,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1
2,1674737,5,2,4,2,24,1,7,82,82,7750,1,1,0,2,1.00000,0.000000,0.000000,1
3,1675224,8,2,1,2,16,0,5,124,124,0,1,1,0,0,1.00000,0.000000,0.000000,1
4,1689785,2,0,4,2,69,0,11,91,13,69756,1,1,0,2,0.00000,0.141125,0.000000,4

In [11]:
necessary_cols=[]
necessary_cols=[cols for cols in data.columns if cols not in ['Opportunity Number','Opportunity Result']]
print(necessary_cols)

['Supplies Subgroup', 'Supplies Group', 'Region', 'Route To Market', 'Elapsed Days In Sales Stage', 'Sales Stage Change Count', 'Total Days Identified Through Closing', 'Total Days Identified Through Qualified', 'Opportunity Amount USD', 'Client Size By Revenue', 'Client Size By Employee Count', 'Revenue From Client Past Two Years', 'Competitor Type', 'Ratio Days Identified To Total Days', 'Ratio Days Validated To Total Days', 'Ratio Days Qualified To Total Days', 'Deal Size Category']

In [12]:
new_data=data[necessary_cols]
# new_data=[cols for cols in data.columns if cols not in ['Opportunity Number','Opportunity Result']]
new_data.head()

,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,2,0,3,0,76,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,2,0,4,2,63,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1
2,5,2,4,2,24,7,82,82,7750,1,1,0,2,1.00000,0.000000,0.000000,1
3,8,2,1,2,16,5,124,124,0,1,1,0,0,1.00000,0.000000,0.000000,1
4,2,0,4,2,69,11,91,13,69756,1,1,0,2,0.00000,0.141125,0.000000,4

In [13]:
data.head(2)#Displays n no of data

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,2,0,3,0,76,1,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,1658010,2,0,4,2,63,0,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1

In [14]:
result=data['Opportunity Result']
#remove from training to check how accurate data actually is during comparison
from sklearn.model_selection import train_test_split 
train_data,test_data ,train_result,test_result = train_test_split(new_data,result,test_size=0.30,random_state=10)
# training 67 testing 33
#10 random
# print(necessary_cols)
print(train_data.head())

       Supplies Subgroup  Supplies Group  Region  Route To Market  \
58546                  6               2       0                0
38963                  5               2       4                2
56239                  4               0       6                0
18336                  5               2       4                0
73136                  3               0       6                0

       Elapsed Days In Sales Stage  Sales Stage Change Count  \
58546                           49                         2
38963                           25                         3
56239                           67                         4
18336                           63                         2
73136                           23                         2

       Total Days Identified Through Closing  \
58546                                     24
38963                                      3
56239                                     14
18336                                     11
73136                                      0

       Total Days Identified Through Qualified  Opportunity Amount USD  \
58546                                       24                   10000
38963                                        3                    2142
56239                                       14                    5000
18336                                       11                   20000
73136                                        0                  500000

       Client Size By Revenue  Client Size By Employee Count  \
58546                       2                              1
38963                       1                              1
56239                       4                              5
18336                       3                              5
73136                       1                              1

       Revenue From Client Past Two Years  Competitor Type  \
58546                                   0                2
38963                                   0                1
56239                                   0                2
18336                                   0                2
73136                                   0                2

       Ratio Days Identified To Total Days  \
58546                             1.000000
38963                             0.000000
56239                             0.285714
18336                             0.000000
73136                             0.000000

       Ratio Days Validated To Total Days  Ratio Days Qualified To Total Days  \
58546                            0.000000                            0.000000
38963                            1.000000                            0.000000
56239                            0.142857                            0.571429
18336                            1.000000                            0.000000
73136                            0.000000                            0.000000

       Deal Size Category
58546                   2
38963                   1
56239                   1
18336                   2
73136                   7

In [15]:
from sklearn.naive_bayes import GaussianNB as gnb
from sklearn.metrics import accuracy_score as acc_sc

In [17]:
gaussian_nb=gnb()
prediction= gaussian_nb.fit(train_data, train_result).predict(test_data)
print(prediction)
model= gaussian_nb.fit(train_data, train_result)
prediction=model.predict(test_data)

[0 0 0 ... 0 0 1]

In [1]:
accuracy=acuracy_score(test_result,predicted_result,normalize=True)

NameError: name 'acuracy_score' is not defined